from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

from .profiles import LLMProfile


class ProfileStore:
    """Persistence for LLM profiles with SQLite fallback and PostgreSQL support.

    SQLite remains the zero-configuration development backend. Production workers
    may share a PostgreSQL database by setting ``TONMEN_KNOWLEDGE_DATABASE_URL``.
    """

    _COLUMNS: tuple[str, ...] = (
        "name",
        "format",
        "base_url",
        "proxy",
        "model",
        "api_key",
        "api_key_hint",
        "rate_per_second",
        "rate_per_minute",
        "context_window_k",
        "thinking_type",
        "reasoning_effort",
        "is_default",
        "priority",
        "pool_exclude",
        "streaming",
        "max_tokens",
        "max_tokens_field",
        "session_header_key",
    )

    def __init__(self, *, database_url: str | None = None, path: str | Path | None = None) -> None:
        self.database_url = (
            str(database_url or os.getenv("TONMEN_KNOWLEDGE_DATABASE_URL", "") or "").strip()
        )
        self.path = Path(path) if path is not None else Path.home() / ".tonmen" / "profiles.db"

    @property
    def backend(self) -> str:
        if self.database_url.startswith(("postgresql://", "postgres://")):
            return "postgres"
        return "sqlite"

    def _connect(self):
        if self.backend == "postgres":
            try:
                import psycopg
            except ImportError as exc:
                raise RuntimeError(
                    "PostgreSQL profile storage requires psycopg; install project dependencies"
                ) from exc
            connection = psycopg.connect(self.database_url)
            self._ensure_schema(connection)
            return connection

        self.path.parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(self.path)
        self._ensure_schema(connection)
        return connection

    def _ensure_schema(self, connection) -> None:
        if self.backend == "postgres":
            statement = """
                CREATE TABLE IF NOT EXISTS llm_profiles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL DEFAULT '',
                    format TEXT NOT NULL DEFAULT 'openai',
                    base_url TEXT,
                    proxy TEXT,
                    model TEXT NOT NULL DEFAULT '',
                    api_key TEXT,
                    api_key_hint TEXT,
                    rate_per_second DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    rate_per_minute DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                    context_window_k INTEGER NOT NULL DEFAULT 0,
                    thinking_type TEXT,
                    reasoning_effort TEXT,
                    is_default BOOLEAN NOT NULL DEFAULT FALSE,
                    priority INTEGER NOT NULL DEFAULT 0,
                    pool_exclude BOOLEAN NOT NULL DEFAULT FALSE,
                    streaming BOOLEAN NOT NULL DEFAULT TRUE,
                    max_tokens INTEGER NOT NULL DEFAULT 0,
                    max_tokens_field TEXT,
                    session_header_key TEXT
                )
            """
        else:
            statement = """
                CREATE TABLE IF NOT EXISTS llm_profiles (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL DEFAULT '',
                    format TEXT NOT NULL DEFAULT 'openai',
                    base_url TEXT,
                    proxy TEXT,
                    model TEXT NOT NULL DEFAULT '',
                    api_key TEXT,
                    api_key_hint TEXT,
                    rate_per_second REAL NOT NULL DEFAULT 0.0,
                    rate_per_minute REAL NOT NULL DEFAULT 0.0,
                    context_window_k INTEGER NOT NULL DEFAULT 0,
                    thinking_type TEXT,
                    reasoning_effort TEXT,
                    is_default INTEGER NOT NULL DEFAULT 0,
                    priority INTEGER NOT NULL DEFAULT 0,
                    pool_exclude INTEGER NOT NULL DEFAULT 0,
                    streaming INTEGER NOT NULL DEFAULT 1,
                    max_tokens INTEGER NOT NULL DEFAULT 0,
                    max_tokens_field TEXT,
                    session_header_key TEXT
                )
            """
        connection.execute(statement)
        connection.commit()

    def _ph(self) -> str:
        return "%s" if self.backend == "postgres" else "?"

    def _row_to_profile(self, row) -> LLMProfile:
        cols = ("id",) + self._COLUMNS
        data = dict(zip(cols, row))
        is_default = data.get("is_default")
        pool_exclude = data.get("pool_exclude")
        streaming = data.get("streaming")
        if self.backend == "sqlite":
            is_default = bool(is_default)
            pool_exclude = bool(pool_exclude)
            streaming = streaming if streaming is None else bool(streaming)
        data["is_default"] = is_default
        data["pool_exclude"] = pool_exclude
        data["streaming"] = streaming
        return LLMProfile.from_row(data)

    def list_profiles(self) -> list[LLMProfile]:
        with self._connect() as connection:
            if self.backend == "postgres":
                with connection.cursor() as cursor:
                    cursor.execute(
                        "SELECT * FROM llm_profiles "
                        "ORDER BY is_default DESC, priority DESC, id ASC"
                    )
                    rows = cursor.fetchall()
            else:
                rows = connection.execute(
                    "SELECT * FROM llm_profiles "
                    "ORDER BY is_default DESC, priority DESC, id ASC"
                ).fetchall()
        return [self._row_to_profile(row) for row in rows]

    def get_profile(self, profile_id: int) -> LLMProfile | None:
        ph = self._ph()
        with self._connect() as connection:
            if self.backend == "postgres":
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"SELECT * FROM llm_profiles WHERE id = {ph}", (profile_id,)
                    )
                    row = cursor.fetchone()
            else:
                row = connection.execute(
                    f"SELECT * FROM llm_profiles WHERE id = {ph}", (profile_id,)
                ).fetchone()
        if row is None:
            return None
        return self._row_to_profile(row)

    def create_profile(self, profile: LLMProfile) -> LLMProfile:
        cols = ", ".join(self._COLUMNS)
        ph = self._ph()
        placeholders = ", ".join(ph for _ in self._COLUMNS)
        values = tuple(profile.as_dict(include_key=True)[c] for c in self._COLUMNS)
        with self._connect() as connection:
            if self.backend == "postgres":
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"INSERT INTO llm_profiles ({cols}) VALUES ({placeholders}) RETURNING id",
                        values,
                    )
                    profile_id = cursor.fetchone()[0]
            else:
                cur = connection.execute(
                    f"INSERT INTO llm_profiles ({cols}) VALUES ({placeholders})", values
                )
                profile_id = cur.lastrowid
        created = self.get_profile(int(profile_id))
        return created if created is not None else profile

    def update_profile(self, profile: LLMProfile) -> LLMProfile:
        ph = self._ph()
        assignments = ", ".join(f"{col} = {ph}" for col in self._COLUMNS)
        values = tuple(profile.as_dict(include_key=True)[c] for c in self._COLUMNS)
        with self._connect() as connection:
            connection.execute(
                f"UPDATE llm_profiles SET {assignments} WHERE id = {ph}",
                values + (profile.id,),
            )
        updated = self.get_profile(profile.id) if profile.id is not None else None
        return updated if updated is not None else profile

    def delete_profile(self, profile_id: int) -> bool:
        ph = self._ph()
        with self._connect() as connection:
            cursor = connection.execute(
                f"DELETE FROM llm_profiles WHERE id = {ph}", (profile_id,)
            )
            return cursor.rowcount > 0

    def set_default(self, profile_id: int) -> None:
        ph = self._ph()
        with self._connect() as connection:
            connection.execute(
                f"UPDATE llm_profiles SET is_default = {ph}", (False,)
            )
            connection.execute(
                f"UPDATE llm_profiles SET is_default = {ph} WHERE id = {ph}",
                (True, profile_id),
            )
